ROMBASESFXDIR:=$(notdir $(SOUNDFXDIR))

SNDFXFILES:=
ifneq (,$(wildcard $(SOUNDFXDIR)))
	SNDFXFILES += $(shell find $(SOUNDFXDIR)/ -name '*.wav' | sed -e 's,'$(SOUNDFXDIR)',$(ROMBASEPATH)/$(ROMBASESFXDIR),g')

$(ROMBASEPATH)/$(ROMBASESFXDIR)/%.wav: $(SOUNDFXDIR)/%.wav
	@mkdir -p $(shell dirname $@)
	cp $< $@
endif
