ROMBASEFONTSDIR:=$(notdir $(FONTSDIR))

EFONTFILES:=
ifneq (,$(wildcard $(FONTSDIR)))
	EFONTFILES += $(shell find $(FONTSDIR)/ -name '*.ttf' | sed -e 's,'$(FONTSDIR)',$(ROMDBASEPATH)/$(ROMBASEFONTSDIR),g')
$(ROMDBASEPATH)/$(ROMBASEFONTSDIR)/%.efont: assets/fonts/%.wav
	@mkdir -p $(shell dirname $@)
	cp $< $@
endif
