ENJ_KOS_CSTD := -std=gnu23
ENJ_CC=kos-cc
ENJ_BASENAME:= $(notdir $(shell pwd))
ENJ_ROMDIR:=cdrom
ENJ_BUILDDIR=build
ENJ_BINDIR=bin
ENJ_CODEDIR:=./code
ENJ_TEXTURE_SRC_DIR:=./assets/texture
ENJ_SOUNDFX_SRC_DIR:=./assets/sfx
ENJ_FONTS_SRC_DIR:=./assets/fonts
ENJ_DEFAULT_OPTLEVEL:=g
ENJ_LDLIBS 	:=
ENJ_INCLUDES=  \
		-I$(KOS_BASE)/utils \
		-I$(shell pwd)/include \
		-I${ENJDIR}/include
ENJ_CFLAGS+=\
		$(ENJ_KOS_CSTD) \

ENJ_ADD_LOGO_TEXTURE:=0
ENJ_INJECT_QFONT:=0