BASENAME:= $(notdir $(shell pwd))
ROMDIR:=cdrom
BUILDDIR=build
TEXTUREDIR:=./assets/texture
SOUNDFXDIR:=./assets/sfx
DEFAULT_OPTLEVEL:=3
LDLIBS 	:=
INCLUDES=  \
		-I$(KOS_BASE)/utils \
		-I$(shell pwd)/include \
		-I$(shell pwd)/enDjinn/include
CFLAGS+=\
		$(KOS_CSTD) \

ADD_ENDJINN_LOGO_TEXTURE:=0
