BASENAME:= $(notdir $(shell pwd))
ROMDIR:=cdrom
ROMDBASEPATH:=$(ROMDIR)/${BASENAME}
BUILDDIR=build
TEXTUREDIR:=./assets/texture
SOUNDFXDIR:=./assets/sfx
DEFAULT_OPTLEVEL:=3
LDLIBS 	:= -lm -lm -lkosutils -lsh4zam
INCLUDES= -I$(KOS_BASE)/include \
		-I$(KOS_BASE)/kernel/arch/dreamcast/include \
		-I$(KOS_BASE)/addons/include \
		-I$(KOS_BASE)/../kos-ports/include \
		-I$(KOS_BASE)/utils \
		-I$(shell pwd)/include \
		-I$(shell pwd)/enDjinn/include
CFLAGS+=\
		$(KOS_CSTD) \
		-D__DREAMCAST__  \
		-D_arch_dreamcast -D_arch_sub_pristine \
		-fstack-protector-all \
		-flto=auto \
		-DFRAME_POINTERS \
		-Wall -Wextra  \
		-fno-strict-aliasing \
		-fomit-frame-pointer \
		-fbuiltin -ffast-math -ffp-contract=fast \
		-mfsrra \
		-mfsca \
		-ml \
		-matomic-model=soft-imask \
		-ffunction-sections -fdata-sections -ftls-model=local-exec \
		-m4-single-only \
		-fms-extensions \
		-fipa-pta 
ADD_ENDJINN_LOGO_TEXTURE:=1