list:
	@LC_ALL=C $(MAKE) -pRrq -f $(firstword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/(^|\n)# Files(\n|$$)/,/(^|\n)# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | grep -E -v -e '^[^[:alnum:]]' -e '^$@$$'


cfg_info:
	@echo "Makefile configurable variables (redefine in $(shell pwd)/Makefile.cfg as necessary):"
	@echo "enDjinn directory: $(ENJDIR)"
	@echo "ENJ_BASENAME      = ${ENJ_BASENAME}"
	@echo "                  # Basename of the target that other names are built from,"
	@echo "                  # defaults to the current directory name."
	@echo "ENJ_TEXTURE_SRC_DIR    = ${ENJ_TEXTURE_SRC_DIR}"
	@echo "                  # Directory containing texture assets"
	@echo "ENJ_SOUNDFX_SRC_DIR    = ${ENJ_SOUNDFX_SRC_DIR}"
	@echo "                  # Directory containing sound effect assets"
	@echo "ENJ_ROMDIR        = ${ENJ_ROMDIR}"
	@echo "                  # Base directory for the CD-ROM image contents" 
	@echo "                  # or for access via dc-tool-ip -m option"
	@echo "ROMBASEPATH  = ${ROMBASEPATH}"
	@echo "                  # Base path inside the CD-ROM image for this project"
	@echo "OPTLEVEL      = ${OPTLEVEL}"
	@echo "                  # Optimization level (default: ${ENJ_DEFAULT_OPTLEVEL})"
	@echo ""
	@echo "Other important make variables:"
	@echo "ENJ_INCLUDES      = ${ENJ_INCLUDES}"
	@echo ""

	@echo "ENJ_LDLIBS        = ${ENJ_LDLIBS}"
	@echo ""

	@echo "ENJ_CFLAGS        = ${ENJ_CFLAGS}"
	@echo ""

auto_variables:
	@echo "Make automatic variables for target ${ENJ_BASENAME}.elf:"
	@echo "\$$ENJ_TEXTURES are:"
	@echo "  [${ENJ_TEXTURES}]"
	@echo ""

	@echo "\$$ENJ_SNDFXFILES are:"
	@echo "  [${ENJ_SNDFXFILES}]"
	@echo ""

	@echo "\$$ENJ_FONTFILES are:"
	@echo "  [${ENJ_FONTFILES}]"
	@echo ""


	@echo "\$$DEFINES are:"
	@echo "  [${DEFINES}]"
	@echo ""

	@echo "\$$OBJS are:"
	@echo "  [${OBJS}]"
	@echo ""

help:
	@echo "make [TARGET] where TARGET is one of:"
	@echo "  ${ENJ_BASENAME}.elf        Build all part_*.elf files"
	@echo "  clean        						Remove all built files"
	@echo "  help         						Show this help message"
	@echo "  list         						List all make targets"
	@echo "  cfg_info         					Show redefineable makefile variables"
	@echo "  cmdline_info          				Alias for ${ENJ_BASENAME}.elf"
