ROMBASESFXDIR:=$(notdir $(FONTSDIR))

EFONTFILES:=
ifneq (,$(wildcard $(FONTSDIR)))
	EFONTFILES += $(shell find $(FONTSDIR)/ -name '*.ttf' | sed -e 's,'$(FONTSDIR)',$(ROMDBASEPATH)/$(ROMBASESFXDIR),g')

$(ROMDBASEPATH)/$(ROMBASESFXDIR)/%.efont: assets/fonts/%.wav
	@mkdir -p $(shell dirname $@)
	cp $< $@
endif
